In [ ]:
import pandas as pd

# 1) Baca CSV (punyamu pakai pemisah ';')
df = pd.read_csv("/content/persentase_telepon_seluler_per_wilayah (1).csv", sep=';')

# kalau di Colab setelah upload biasanya jadi:
# df = pd.read_csv("persentase_telepon_seluler_per_wilayah (1).csv", sep=';')

# 2) Pastikan tipe data benar
df["Tahun"] = df["Tahun"].astype(int)

# 3) Bikin urutan kategori segmentasi: Perkotaan dulu, baru Perdesaan
order_seg = ["Perkotaan", "Perdesaan"]
df["Segmentasi Wilayah"] = pd.Categorical(
    df["Segmentasi Wilayah"],
    categories=order_seg,
    ordered=True
)

# 4) Sort sesuai kebutuhanmu
df_sorted = df.sort_values(
    ["Provinsi", "Segmentasi Wilayah", "Tahun"],
    ascending=[True, True, False]
).reset_index(drop=True)

# 5) Lihat hasil (contoh Aceh & Bali)
display(df_sorted[df_sorted["Provinsi"].isin(["Aceh", "Bali"])].head(20))

# 6) (opsional) Simpan hasil yang sudah rapi
df_sorted.to_csv("data_urut.csv", index=False, sep=';')
print("Saved -> data_urut.csv")

   Provinsi  Tahun Segmentasi Wilayah  Persentase
0      Aceh   2024          Perkotaan        9644
1      Aceh   2023          Perkotaan        9479
2      Aceh   2022          Perkotaan        9483
3      Aceh   2021          Perkotaan        9467
4      Aceh   2020          Perkotaan        9622
5      Aceh   2024          Perdesaan        9307
6      Aceh   2023          Perdesaan        8946
7      Aceh   2022          Perdesaan        9106
8      Aceh   2021          Perdesaan        8974
9      Aceh   2020          Perdesaan        9034
10     Bali   2024          Perkotaan         975
11     Bali   2023          Perkotaan        9578
12     Bali   2022          Perkotaan        9714
13     Bali   2021          Perkotaan        9619
14     Bali   2020          Perkotaan        9695
15     Bali   2024          Perdesaan        9029
16     Bali   2023          Perdesaan        8776
17     Bali   2022          Perdesaan        9295
18     Bali   2021          Perdesaan        8894
19     Bali   2020          Perdesaan        8814

Saved -> data_urut.csv

In [ ]:
df_sorted["Persentase"] = df_sorted["Persentase"] / 100
df_sorted["Persentase"] = df_sorted["Persentase"].apply(lambda x: f"{x:.2f}".replace(".", ","))

display(df_sorted[df_sorted["Provinsi"].isin(["Aceh", "Bali"])].head(20))

   Provinsi  Tahun Segmentasi Wilayah Persentase
0      Aceh   2024          Perkotaan      96,44
1      Aceh   2023          Perkotaan      94,79
2      Aceh   2022          Perkotaan      94,83
3      Aceh   2021          Perkotaan      94,67
4      Aceh   2020          Perkotaan      96,22
5      Aceh   2024          Perdesaan      93,07
6      Aceh   2023          Perdesaan      89,46
7      Aceh   2022          Perdesaan      91,06
8      Aceh   2021          Perdesaan      89,74
9      Aceh   2020          Perdesaan      90,34
10     Bali   2024          Perkotaan       9,75
11     Bali   2023          Perkotaan      95,78
12     Bali   2022          Perkotaan      97,14
13     Bali   2021          Perkotaan      96,19
14     Bali   2020          Perkotaan      96,95
15     Bali   2024          Perdesaan      90,29
16     Bali   2023          Perdesaan      87,76
17     Bali   2022          Perdesaan      92,95
18     Bali   2021          Perdesaan      88,94
19     Bali   2020          Perdesaan      88,14

In [ ]:
df_sorted.to_csv("data_urut_persen.csv", index=False, sep=';')
print("Saved -> data_urut_persen.csv")

Saved -> data_urut_persen.csv